### ISSUE TITLE
Get graphs working 

### ISSUE THREAD

**Issue by philzook58** [perciplex/raas#11]
We need to transport info over to the server

I think we should save data in the gym env
save it to the logs folder

**Comment by ishmandoo** [comment]
I would say this data should be sent back to the server when jobs are complete, separate from the logs.

**Comment by philzook58** [comment]
we need to set up a logs folder and mount a subdirectory?
I put a pickling thing into gym-env but it'll definitely crash if log/ isnt there

**Comment by ishmandoo** [comment]
Now saving the logs in a json file, mounted in the docker container
