### ISSUE TITLE
raas-decision-tree run not running

### ISSUE THREAD

**Issue by declanoller** [perciplex/raas#31]
When I submit https://github.com/perciplex/raas-decision-tree , it appears in the queue, and then says it's running. Then it disappears. @MaximilianKing has more info (something about it failing to pull the repo?).

Definitely something to solve before MSP.

**Comment by declanoller** [comment]
Just to be sure: even if someone's program has a python bug and crashes, it should still produce stdout with the error and such, right?

**Comment by MaximilianKing** [comment]
Recent tests show that it may be working? Not sure 100% what has fixed it, but will close for now unless issue re-appears
