### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by philzook58** [perciplex/raas#4]
Minimal:

- [x] We have a motor with encoder and cheap motor drivers and a aluminum faceplate and PAINT STIRRER RODS
- [x] ~3d printed parts? They don't seem to last.~
- [x] Need external to docker driver software. I suggest communication to docker using ZeroMQ. But maybe someonce should investitage an appropriate technology for this
- [x] Make Bill of Materials and build guide. The idea is that anyone can make our open source stuff.

Next Step:

- [ ] robustify. 
- [ ] Make electronics board hat that is actually soldered together

**Comment by MaximilianKing** [comment]
We dont actually want 3d printed parts.
